### ISSUE TITLE
Libraries are imported that aren't dependencies.

### ISSUE THREAD

**Issue by irgeek** [GitGuardian/py-gitguardian#43]
Commit 9642af5 added imports for libraries that aren't actually dependencies for `pygitguardian`. Specifically, these imports:

https://github.com/GitGuardian/py-gitguardian/blob/183784df9a4cc6770bab4c7e04dedb20f0eb0d13/pygitguardian/client.py#L9

https://github.com/GitGuardian/py-gitguardian/blob/183784df9a4cc6770bab4c7e04dedb20f0eb0d13/tests/test_utils.py#L5

https://github.com/GitGuardian/py-gitguardian/blob/183784df9a4cc6770bab4c7e04dedb20f0eb0d13/pygitguardian/iac_models.py#L4

It seems reasonable that `marshmallow-dataclass` should be added as a dependency for an API client, but I think making `click` a dependency would limit the usefulness. I suspect removing `click` will require modifications to `ggshield`.

**Comment by agateau-gg** [comment]
Thanks for this report, going to look into it.
