### ISSUE TITLE
Only for scanning, no incident management/retrieve findings ?

### ISSUE THREAD

**Issue by Gby56** [GitGuardian/py-gitguardian#82]
It seems that the client here doesn't have a lot of coverage of the overall https://api.gitguardian.com/docs

Maybe I'll try a generated client from the API spec, but I thought this client was supporting more operations

**Comment by agateau-gg** [comment]
Hi, the client is definitely not complete indeed. It's main use is supporting ggshield access to the API.

It's not a hard rule, we just concentrate on our needs for ggshield. If you feel like contributing support for other parts of the API, it would be most welcomed.
